[colors.primary]
background = "#1C1E26"
foreground = "#CBCCD3"

[colors.normal]
black = "#43444D"
red = "#283455"
green = "#2C3657"
yellow = "#303958"
blue = "#343B5A"
magenta = "#40425F"
cyan = "#6A6C82"
white = "#ACADB8"

[colors.bright]
black = "#787981"
red = "#283455"
green = "#2C3657"
yellow = "#303958"
blue = "#343B5A"
magenta = "#40425F"
cyan = "#6A6C82"
white = "#ACADB8"