[colors.primary]
background = "#18171D"
foreground = "#F5B7EE"

[colors.normal]
black = "#403E45"
red = "#181332"
green = "#28134F"
yellow = "#591D7D"
blue = "#7C1AC8"
magenta = "#786EBB"
cyan = "#E231CF"
white = "#E890DF"

[colors.bright]
black = "#A2649C"
red = "#181332"
green = "#28134F"
yellow = "#591D7D"
blue = "#7C1AC8"
magenta = "#786EBB"
cyan = "#E231CF"
white = "#E890DF"